---
title: "mice1"
author: "Leo-Yu-8859"
date: "2021/7/8"
output: html_document
---
```{r}
library(mice)
```
# DEFAULT
## 1. Check **nhanes** from mice
```{r}
head(nhanes, 3)
md.pattern(nhanes)
```

## 2. Start imputing
```{r}
imp <- mice(nhanes, seed = 23109)
imp
```

## 3. Diagnostic
```{r}
imp$imp$bmi  ## five imputations for bmi
complete(imp)  ## first completed dataset
complete(imp, 2)  ## second completed dataset
stripplot(imp, pch = 20, cex = 1.2)
xyplot(imp, bmi ~ chl | .imp, pch = 20, cex = 1.4)
```

## 4. Analysis
```{r}
fit <- with(imp, lm(chl ~ age + bmi))
pool(fit)
summary(pool(fit))
```

#### Use a higher number of imputations to minimize simulation error.
```{r}
imp50 <- mice(nhanes, seed = 23109, m = 50)
fit50 <- with(imp50, lm(chl ~ age + bmi))
pool(fit50)
summary(pool(fit50))
```

# ADVANCED
## 1. Removing a predictor
####For example, suppose that bmi is considered irrelevant as a predictor.
```{r}
pred <- imp$predictorMatrix
pred[, "bmi"] <- 0
pred
imppred <- mice(nhanes, predictorMatrix = pred, print = FALSE)
```
